name: Run Benchmarks Single
on:
  pull_request:
  workflow_dispatch:
    inputs:
      runTimes:
        description: 'Test run times'
        required: true
        default: 1
        type: choice
        options:
        - 1
        - 5
        - 10
      Warmup:
        description: 'Warmup times'
        required: true
        default: 1
        type: choice
        options:
        - 0
        - 1
        - 3
jobs:
  benchmark-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v1
      
      - name: Install
        run: |
          # Install dependencies
          npm install pnpm -g
          pnpm install

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb

      - name: Run jest
        run: |
          hyperfine --warmup ${{ inputs.Warmup }} --runs  ${{ inputs.runTimes }} \
          'pnpm run test:jest'
      - name: Run jest --runInBand
        run: |
          hyperfine --warmup ${{ inputs.Warmup }} --runs ${{ inputs.runTimes }} \
          'pnpm run test:jest:inline'
      - name: Run vitest
        run: |
          hyperfine --warmup ${{ inputs.Warmup }} --runs ${{ inputs.runTimes }} \
          'pnpm run test:vitest'
      - name: Run vitest --poolOptions.threads.singleThread=true
        run: |
          hyperfine --warmup ${{ inputs.Warmup }} --runs ${{ inputs.runTimes }} \
          'pnpm run test:vitest:inline'

      - name: Output
        run: |
          cat /home/runner/work/_actions/catchpoint/workflow-telemetry-action/v1/dist/proc-tracer/proc-trace.out
